/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta/scope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scope Statement
         * @description What this build covers and what it refuses, computed from the build itself.
         *
         *     Never asks the database. `cached_status` is what the startup check and the
         *     health poll already filled in, so an instance that has not finished starting
         *     reports `schema_not_checked` rather than blocking on a connection.
         */
        get: operations["scope_statement_api_v1_meta_scope_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tax/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Tax Question
         * @description Ask a question about German taxes and get a cited answer.
         *
         *     - **text**: The tax question
         *     - **language**: Response language (auto, en, de, tr, ru)
         *     - **context**: Optional context about the user (marital status, income, etc.)
         *
         *     The response carries the `request_id` that identifies this request in the
         *     server logs; POST it back to /feedback to attach a rating to it.
         *
         *     Rate limited per client and globally (see `core/rate_limit.py`); over the
         *     limit the response is a 429 carrying `Retry-After`.
         *
         *     Errors follow the contract `{"detail": <safe text>, "error_code": <CODE>}`
         *     via the global exception handlers in main.py (VALIDATION_ERROR,
         *     RATE_LIMITED, LLM_PROVIDER_ERROR, INTERNAL_ERROR); internals are logged, not
         *     returned.
         */
        post: operations["ask_tax_question_api_v1_tax_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tax/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Feedback
         * @description Record a 👍/👎 on a previous answer.
         *
         *     Ratings are written to the log against the answer's `request_id`, which is
         *     what makes them joinable with that request's retrieval strategies, tools and
         *     token usage. Free-text comments are redacted before logging — a user
         *     explaining a wrong answer will quote their own salary while doing it.
         */
        post: operations["submit_feedback_api_v1_tax_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tax/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         *
         *     Still 200 when the schema has drifted, and deliberately so: this is the path
         *     Render polls, a non-200 takes the instance out of service, and drift stops Tax
         *     Cases without stopping the chat tab. The status body is what says so - "status"
         *     stays "ok" for the process, and "schema" carries the bad news.
         *
         *     It reports what is already known and never asks the database itself: this route
         *     is polled, and the default test run has to work offline. The startup check fills
         *     that in, and a drifted answer goes stale on its own, so "not_checked" here means
         *     nobody has looked yet - which is the truth on an instance that has not finished
         *     starting.
         */
        get: operations["health_check_api_v1_tax_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_v1_cases_get"];
        put?: never;
        /** Create Case */
        post: operations["create_case_api_v1_cases_post"];
        /**
         * Delete All Cases
         * @description Every Tax Case this user has, gone - tables and paused runs alike.
         *
         *     Goes on past a case it cannot delete, so one stuck case does not stand between
         *     the user and the rest of theirs. 204 therefore means all of them; a 500 names how
         *     many are left and the request can simply be repeated.
         *
         *     What it does not touch: the profile memory, which outlives cases on purpose
         *     (#23), and the chat history in this browser (#18). The confirmation text says so.
         */
        delete: operations["delete_all_cases_api_v1_cases_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_api_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Case
         * @description The product's promise made callable: a case and everything in it, gone.
         *
         *     "Everything in it" now means both stores that hold the answers - the tables and
         *     the paused graph run - and 204 is returned only once both are clear. Deleting a
         *     case that is already gone is a 404, not a silent success: the caller asked about
         *     a case this user does not have, and that is worth saying.
         *
         *     What survives is listed and argued for in `services/case_erasure.py`.
         */
        delete: operations["delete_case_api_v1_cases__case_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/interview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance Interview */
        post: operations["advance_interview_api_v1_cases__case_id__interview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/interview/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance Interview Stream */
        post: operations["advance_interview_stream_api_v1_cases__case_id__interview_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/anlage-n.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Anlage N
         * @description The case as the official Anlage N, filled in.
         *
         *     The report has always been able to say "Zeile 58"; this is that sentence carried
         *     out. The figures are the same ones the dashboard shows and the Reviewer audited —
         *     `expense_rows` produces them once and everything downstream reads them — so the
         *     PDF cannot disagree with the screen.
         *
         *     It is a draft and says so on the page. Nothing here files anything, the blank is
         *     the published form and not a facsimile, and any figure the form has no single
         *     unambiguous box for comes back in a header rather than being quietly dropped.
         */
        get: operations["download_anlage_n_api_v1_cases__case_id__anlage_n_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/interview/back": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step Back
         * @description Undo the last answer and ask its question again.
         *
         *     The checkpointer has been recording a snapshot per step since the first
         *     interview; this endpoint is the first thing to read it backwards. Going back
         *     means replaying the run from the checkpoint at which that question was on
         *     screen — the graph re-runs the paused node, pauses on the same question, and
         *     every later checkpoint is simply no longer the head. The answer itself is
         *     deleted from the case, so the tables and the run agree about what is known.
         *
         *     No provider call happens: the replayed node is `ask_user`, which does nothing
         *     but pause. It is rate limited all the same, because it is still a write.
         */
        post: operations["step_back_api_v1_cases__case_id__interview_back_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description This case's documents, expiring any that waited too long for a decision.
         */
        get: operations["list_documents_api_v1_cases__case_id__documents_get"];
        put?: never;
        /**
         * Upload Document
         * @description Read one document and stop, waiting for the user to confirm what it said.
         *
         *     Everything that needs the bytes - the format checks and both extraction passes -
         *     happens inside this request. The run then pauses, and the bytes go out of scope
         *     with it (ADR 0004).
         */
        post: operations["upload_document_api_v1_cases__case_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/documents/{document_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Document
         * @description Write the values the user settled on, and forget the document.
         *
         *     The provenance of each value is decided here from the paused run's own proposal,
         *     not from the request: a reading left as it stands is a `document` value, a
         *     corrected or typed one is an `answer` (issue #12). A client cannot claim
         *     otherwise, because it is not asked.
         */
        post: operations["confirm_document_api_v1_cases__case_id__documents__document_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/documents/{document_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discard Document
         * @description Throw the reading away. The row stays, saying an upload was rejected.
         */
        post: operations["discard_document_api_v1_cases__case_id__documents__document_id__discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Forget Me
         * @description Delete everything the system remembers about this person between years.
         *
         *     Deliberately not part of deleting a case, and deliberately not implied by it.
         *     Someone who finishes a year and deletes the case usually still wants next year to
         *     be short; someone who wants to be forgotten wants that whether or not a case
         *     survives. `services/case_erasure.py` leaves this store alone for the same reason.
         *
         *     204 with nothing remembered is the right answer, not an error: they asked for
         *     there to be nothing, and there is nothing.
         *
         *     No `require_schema` here, unlike the case router. This store is LangGraph's own
         *     table, created by the library rather than by a file in `db/schema/`, so the
         *     schema ledger has nothing to say about it - and refusing to forget somebody
         *     because an unrelated migration is outstanding would be the wrong way round.
         */
        delete: operations["forget_me_api_v1_profile_memory_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CaseDetailResponse */
        CaseDetailResponse: {
            /** Id */
            id: string;
            /** Tax Year */
            tax_year: number;
            /** Status */
            status: string;
            /** Fields */
            fields: Record<string, never>;
            /** Unconfirmed Values */
            unconfirmed_values: string[];
            /** Expenses */
            expenses: Record<string, never>[];
            /** Proposed Expenses */
            proposed_expenses: Record<string, never>[];
            /** Tax Positions */
            tax_positions: Record<string, never>[];
            /** Total Eur */
            total_eur: number;
            /** Proposed Total Eur */
            proposed_total_eur: number;
            /** Pauschbetrag Eur */
            pauschbetrag_eur: number;
            /** Gaps */
            gaps: Record<string, never>[];
            /** Findings */
            findings: Record<string, never>[];
        };
        /** CaseResponse */
        CaseResponse: {
            /** Id */
            id: string;
            /** Tax Year */
            tax_year: number;
            /** Status */
            status: string;
        };
        /**
         * ConfirmRequest
         * @description What the user settled on. Keys and values are validated, never trusted.
         */
        ConfirmRequest: {
            /** Values */
            values?: Record<string, never>;
            /** Category */
            category?: string | null;
        };
        /** CreateCaseRequest */
        CreateCaseRequest: {
            /** Tax Year */
            tax_year: number;
        };
        /**
         * DataScope
         * @description What using a mode leaves behind, named one store at a time.
         *
         *     Three fields rather than one boolean, and the fourth store - the browser's own
         *     chat history - deliberately absent: this process cannot see a localStorage and
         *     must not claim anything about it.
         */
        DataScope: {
            /** Server */
            server: string;
            /** Profile Memory */
            profile_memory: string;
            /** Tracing */
            tracing: string;
        };
        /**
         * DocumentResponse
         * @description One document as a screen needs it.
         */
        DocumentResponse: {
            /** Id */
            id: string;
            /** File Name */
            file_name: string;
            /** Kind */
            kind?: string | null;
            /** State */
            state: string;
            /** Proposed */
            proposed?: Record<string, never>[];
            /** Questions */
            questions?: string[];
            /** Disagreements */
            disagreements?: string[];
            /** Category */
            category?: string | null;
            /**
             * Category Reason
             * @default
             */
            category_reason: string;
            /** Contradiction */
            contradiction?: string | null;
            /** Category Choices */
            category_choices?: string[];
            /** Failure Code */
            failure_code?: string | null;
            /** Failure Detail */
            failure_detail?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
            /** Error Code */
            error_code: string;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Request Id */
            request_id: string;
            /** Rating */
            rating: string;
            /** Comment */
            comment?: string | null;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /**
             * Status
             * @default recorded
             */
            status: string;
        };
        /**
         * FormScope
         * @description A form this build can place figures on, and how sure it is of the lines.
         */
        FormScope: {
            /** Form */
            form: string;
            /** Categories */
            categories: string[];
            /** Lines Verified */
            lines_verified: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryTurn
         * @description One earlier turn of the conversation, as replayed by the client.
         */
        HistoryTurn: {
            /** Role */
            role: string;
            /** Text */
            text: string;
        };
        /** InterviewRequest */
        InterviewRequest: {
            /** Resume */
            resume?: unknown | null;
        };
        /** InterviewResponse */
        InterviewResponse: {
            /** Status */
            status: string;
            /** Pause */
            pause?: Record<string, never> | null;
            /**
             * Done
             * @default false
             */
            done: boolean;
            /** Debug */
            debug?: Record<string, never> | null;
        };
        /**
         * ModeScope
         * @description One of the two things a visitor can do, and whether they can do it here.
         */
        ModeScope: {
            /** Id */
            id: string;
            /** Available */
            available: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Requires Account */
            requires_account: boolean;
            storage: components["schemas"]["DataScope"];
        };
        /**
         * ScopeResponse
         * @description The whole statement. One request, everything a visitor is owed up front.
         */
        ScopeResponse: {
            /** Modes */
            modes: components["schemas"]["ModeScope"][];
            /** Tax Years */
            tax_years: components["schemas"]["TaxYearScope"][];
            /** Default Tax Year */
            default_tax_year: number;
            /** Limits */
            limits: {
                [key: string]: number;
            };
            /** Not Supported */
            not_supported: string[];
        };
        /** SourceResponse */
        SourceResponse: {
            /** Title */
            title: string;
            /**
             * Ref
             * @default
             */
            ref: string;
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Source Id
             * @default
             */
            source_id: string;
            /**
             * Section
             * @default
             */
            section: string;
            /**
             * Snippet
             * @default
             */
            snippet: string;
        };
        /** TaxAnswerResponse */
        TaxAnswerResponse: {
            /** Summary */
            summary: string;
            /** Explanation */
            explanation: string[];
            /** Sources */
            sources: components["schemas"]["SourceResponse"][];
            /** Trace */
            trace?: components["schemas"]["TraceStep"][];
            /**
             * Intent
             * @default knowledge
             */
            intent: string;
            /** Warnings */
            warnings?: string[];
            usage?: components["schemas"]["UsageInfo"];
            /** Tool Results */
            tool_results?: components["schemas"]["ToolResult"][];
            /**
             * Request Id
             * @default
             */
            request_id: string;
        };
        /** TaxQuestionRequest */
        TaxQuestionRequest: {
            /** Text */
            text: string;
            /**
             * Language
             * @default auto
             */
            language: string;
            /**
             * Depth
             * @default balanced
             */
            depth: string;
            /** Context */
            context?: Record<string, never> | null;
            /** History */
            history?: components["schemas"]["HistoryTurn"][];
        };
        /**
         * TaxYearScope
         * @description A year this build has rules for, with the period it may be filed in.
         */
        TaxYearScope: {
            /** Year */
            year: number;
            /** Filing Due */
            filing_due: string;
            /** Filing Due Advised */
            filing_due_advised: string;
            /** Voluntary Filing Until */
            voluntary_filing_until: string;
            /** Forms */
            forms: components["schemas"]["FormScope"][];
        };
        /**
         * ToolResult
         * @description Successful tool execution, structured for card rendering in the UI.
         */
        ToolResult: {
            /** Tool */
            tool: string;
            /** Data */
            data: Record<string, never>;
        };
        /** TraceStep */
        TraceStep: {
            /** Label */
            label: string;
            /** Detail */
            detail: string;
        };
        /** UsageInfo */
        UsageInfo: {
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /**
             * Llm Calls
             * @default 0
             */
            llm_calls: number;
            /**
             * Model
             * @default
             */
            model: string;
            /** Cost Usd */
            cost_usd?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    scope_statement_api_v1_meta_scope_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeResponse"];
                };
            };
        };
    };
    ask_tax_question_api_v1_tax_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxAnswerResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    submit_feedback_api_v1_tax_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_v1_tax_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_cases_api_v1_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseResponse"][];
                };
            };
        };
    };
    create_case_api_v1_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_all_cases_api_v1_cases_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_case_api_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_case_api_v1_cases__case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_interview_api_v1_cases__case_id__interview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_interview_stream_api_v1_cases__case_id__interview_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_anlage_n_api_v1_cases__case_id__anlage_n_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    step_back_api_v1_cases__case_id__interview_back_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_cases__case_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_cases__case_id__documents_post: {
        parameters: {
            query: {
                kind: string;
                file_name?: string;
            };
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_document_api_v1_cases__case_id__documents__document_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_document_api_v1_cases__case_id__documents__document_id__discard_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forget_me_api_v1_profile_memory_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
