import { FlatCompat } from "@eslint/eslintrc";
import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

// eslint-config-next still ships an eslintrc-style config, so it needs FlatCompat to load
// here. Without it `next build` warns that the Next.js plugin is not detected and none of
// the Next-specific rules run, even though eslint-config-next is installed.
const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

export default tseslint.config(
  // next-env.d.ts is generated by `next build`; its triple-slash reference is not ours to fix.
  { ignores: ["dist", ".next", "out", "next-env.d.ts"] },
  ...compat.extends("next/core-web-vitals"),
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  eslintPluginPrettier,
);
