#!/usr/bin/env python3
"""Regenerate docs/KB_INDEX.md from the KB frontmatter.

The index keeps the KB inventory visible instead of assumed: eval expectations
are authored against it, and test_golden_references_exist_in_the_kb enforces the
same set. Run after any change to KB/:

    python3 scripts/kb-index.py
"""

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
KB = ROOT / "KB"
OUT = ROOT / "docs" / "KB_INDEX.md"


def main() -> None:
    rows = []
    for f in sorted(KB.glob("*.md")):
        front_match = re.match(r"^---\n(.*?)\n---", f.read_text(errors="ignore"), re.S)
        front = front_match.group(1) if front_match else ""
        sid = re.search(r"source_id:\s*(\S+)", front)
        topics = re.search(r"topics:\s*\[([^\]]*)\]", front)
        rows.append((f.name, sid.group(1) if sid else "(no source_id!)",
                     topics.group(1) if topics else ""))
    pdfs = sorted(p.name for p in KB.iterdir() if p.suffix.lower() == ".pdf")

    lines = [
        "# Knowledge base index",
        "",
        "Generated by `scripts/kb-index.py` from the `KB/*.md` frontmatter, so the",
        "inventory is visible rather than assumed: eval expectations are authored",
        "against this list, and `test_golden_references_exist_in_the_kb` refuses a",
        "reference to a document that is not here. Regenerate after any KB change.",
        "",
        f"Markdown documents (ingested): **{len(rows)}**. PDFs (human reference only,",
        f"never retrieved): **{len(pdfs)}**.",
        "",
        "| file | source_id | topics |",
        "|---|---|---|",
    ]
    lines += [f"| {name} | `{sid}` | {topics} |" for name, sid, topics in rows]
    lines += ["", "## PDFs (not retrieved)", ""]
    lines += [f"- {p}" for p in pdfs]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{OUT.relative_to(ROOT)}: {len(rows)} md, {len(pdfs)} pdf")
    ghosts = [name for name, sid, _ in rows if sid.startswith("(")]
    if ghosts:
        raise SystemExit(f"documents without source_id: {ghosts}")


if __name__ == "__main__":
    main()
